- hosts: master
  become: true
  roles:
    - oracle-java
    - init
    - ansible-wildfly
    - driver
    - master
- hosts: slave
  become: true
  roles:
    - oracle-java
    - init
    - ansible-wildfly
    - driver
    - slave
