- hosts: master
  become: true
  roles:
    - oracle-java
    - init
    - ansible-wildfly
    - master
    - driver
    - driver-master
- hosts: slave
  become: true
  roles:
    - oracle-java
    - init
    - ansible-wildfly
    - slave
    - driver
- hosts: master,slave
  become: ture
  roles:
    - finalstep