- hosts: master
  become: true
  roles:
    - init
    - ansible-wildfly
    - master
- hosts: slave
  become: true
  roles:
    - init
    - ansible-wildfly
    - slave
- hosts: slave2
  become: true
  roles:
    - init
    - ansible-wildfly
    - slave2
