- name: IPTABLES
  tasks:
    - name: Aprire le corrette porte per l'IPTables
      lineinfile: dest=/etc/sysconfig/iptables-config
                  regexp="^-A INPUT -m state --state NEW -m {{item.protocol}} -p {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
                  line="-A INPUT -m state --state NEW -m {{item.protocol}} -p {{item.protocol}} --dport {{item.port}} -j ACCEPT"
                  insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
      with_items:
        - { protocol: tcp, port: 80 }
        - { protocol: tcp, port: 22 }
      notify:
        - restart iptables
  handlers:
      - name: restart iptables
        action: systemctl name=iptables state=restarted
- name: Disable SELINUX

  selinux:
    policy: targeted
    state: permissive

# Disable SELinux
- selinux:
    state: disabled
- name: stop firewalld
  service: name=firewalld state=stopped enabled=no
