- name: Configurazione host-slave.xml
  template:
    src: host-slave.file
    dest: /opt/wildfly-{{ wildfly_version }}.Final/domain/configuration/host-slave.xml
    owner: wildfly
    group: wildfly
- replace:
    path: /opt/wildfly-{{ wildfly_version }}.Final/domain/configuration/host-slave.xml
    regexp: "masterip"
    replace: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
  with_items:
    - "{{ groups['master'] }}"
#widlfly.conf
- name: wildfly.conf
  template:
    src: wildfly-slave.conf
    dest: /etc/default/wildfly.conf
    owner: wildfly
    group: wildfly
#wildfly.service
- name: wildfly service
  template:
    src: wildfly.service
    dest: /etc/systemd/system/wildfly.service
    owner: wildfly
    group: wildfly
#file initd versione 10
- name: init.d
  template:
    src: init.d
    dest: /opt/wildfly-{{ wildfly_version }}.Final/bin/init.d/wildfly-init-redhat.sh
    owner: wildfly
    group: wildfly
- name: reload daemon systemctl
  systemd: daemon_reload=yes
