- name: Configurazione host-master.xml
  template:
    src: host-master.file
    dest: /opt/wildfly-11.0.0.Final/domain/configuration/host-master.xml
    owner: wildfly
    group: wildfly
- replace:
    path: /opt/wildfly-11.0.0.Final/domain/configuration/host-master.xml
    regexp: "IPMASTER"
    replace: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
  with_items:
    - "{{ groups['master'] }}"
#Host config
- name: Configurazione host.xml
  template:
    src: host.file
    dest: /opt/wildfly-11.0.0.Final/domain/configuration/host.xml
    owner: wildfly
    group: wildfly
- replace:
    path: /opt/wildfly-11.0.0.Final/domain/configuration/host.xml
    regexp: "IPMASTER"
    replace: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
  with_items:
    - "{{ groups['master'] }}"
#secret.sh
- name: Creazione sh secret
  template:
    src: secret.file
    dest: /opt/wildfly-11.0.0.Final/bin/secret.sh
    mode: 0755
    owner: wildfly
    group: wildfly
#./add-user.sh
- name: Avvio add-user.sh
  command: /opt/wildfly-11.0.0.Final/bin/secret.sh
  register: wildfly_secret

- set_fact:
    wildfly_secret_set: "{{wildfly_secret.stdout_lines}}"
#widlfly.conf
- name: wildfly config
  template:
    src: wildfly-master.conf
    dest: /etc/default/wildfly.conf
    owner: wildfly
    group: wildfly
#wildfly.service
- name: wildfly service
  template:
    src: wildfly.service
    dest: /etc/systemd/system/wildfly.service
    owner: wildfly
    group: wildfly
#file initd versione 10
- name: init.d
  template:
    src: init.d
    dest: /opt/wildfly-11.0.0.Final/bin/init.d/wildfly-init-redhat.sh
    owner: wildfly
    group: wildfly
- name: reload daemon systemctl
  systemd: daemon_reload=yes
